#!/bin/bash

# Declaring a few misc variables
vspiversion=2.0 # SPI version
vspibuild=2017 # SPI build number
vbranch=Stable # SPI build branch
vsysarch=$(getconf LONG_BIT) # System architecture

# Function for iptables rules (CentOS 7, Debian, Ubuntu, Fedora)
firew2 ()	{
	# Opening default Squid port 3128 for clients to connect
	iptables -I INPUT -p tcp --dport 3128 -j ACCEPT
	# Saving firewall rules
	iptables-save
}

# Function for Ubuntu
ubt ()	{
	# Updating package database
	apt-get update
	# Installing necessary packages (Squid, apache2-utils for htpassword and dependencies)
	apt-get install squid -y
	# Asking user to set a username via read and writing it into $usrn
	
	# Creating user with username from $usrn and asking user to set a password
	
	# Downloading Squid configuration
	wget -O /etc/squid/squid.conf https://raw.githubusercontent.com/scheiderr/cccviktor/master/spi-ubuntu.conf --no-check-certificate
	# Copying squid3.conf from init to init.d for startup script
	
	# Creating empty blacklist.acl file for further blacklisting entries
	
	# Restarting Squid and enabling its service
	service squid restart && update-rc.d squid defaults
	# Running function firew2
	firew2
}

# Checking $1 and running corresponding function
case $1 in
	'-ubuntu') # If option "-ubuntu" run function ubt
		ubt;; # Ubuntu
esac
